version: '3.7'
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    privileged: true
    volumes:
     - /data/jenkins/home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
     - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
     - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    ports:
     - "8080:8080"
     - "50000:50000"