version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: docker_jenkins
    volumes:
     - /e/docker/jenkins:/var/jenkins_home
    ports:
     - "8080:8080"
     - "50000:50000"